#:schema node_modules/wrangler/config-schema.json
name = "imguu"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"


# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
[[d1_databases]]
binding = "MY_DB"
database_name = "imguu"
database_id = "a42ef288-a2eb-4ec3-a89c-d371a528fed7"
[[r2_buckets]]
binding = "imguu"
bucket_name = "r2image"